# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f36ed6a91c7affe0fb5d6418806c3fb323d2f8deb642d496dab22c05c0266d7c3e40950d8c86c3273122953a0f8e7b116ede62a792cbd07d0cf3986167db8ac

test:
  secret_key_base: 30f84e19e68c85b4d6fbe54a9f1345ac53f4c7f165496a136b184221849c4fb4bbabfcbaff42d8ac6a23f549fc0141c612c367120e26848d57998010cb6ea7a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
